### ISSUE TITLE
Should binaries be build during package build? Network split due to different underlying libraries?

### ISSUE THREAD

**Issue by adrelanos** [ResistancePlatform/resistance-miner#10]
After bitcoin existing for more than 10 years, being popular and being in Debian `unstable`  (`sid`) it still never made its way into Debian testing.

Reason being explained that a difference in underlying libraries (even just security fixes) may result in a network split.

Binaries compiled during packaging on different versions of Debian and/or Ubuntu might have different libraries that might cause that.

References:
https://packages.debian.org/search?keywords=bitcoin-qt
https://packages.debian.org/sid/bitcoin-qt

Discussion by Debian developers:
[upstream does not support stable releases (block migration to testing)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=718272)

(Note: above website saying `Tags: fixed-upstream` is probably a mistake as discussion at bottom says.)

**Comment by solardiz** [comment]
Are you asking this in context of building the miner or core or both? You've opened the issue for the miner, so I'll reply for the miner: there's absolutely no such risk.

And yes, binaries should be built during package build.

**Comment by solardiz** [comment]
Regarding core, my answer would be more complicated.

**Comment by adrelanos** [comment]
I like the approach of discussion things separately. So created https://github.com/ResistancePlatform/resistance-core/issues/71 for it.

**Comment by solardiz** [comment]
I think this issue is fully discussed for the miner, and can be closed.
